spring:
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp